### ISSUE TITLE
How to obtain version?

### ISSUE THREAD

**Issue by gogasca** [googleapis/python-monitoring#131]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-monitoring/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Linux
  - Python version: `python --version`  3.7.10
  - pip version: `pip --version`
 
```
pip 21.1.1 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
```
  - `google-cloud-monitoring` version: `pip show google-cloud-monitoring`

```
pip show google-cloud-monitoring
Name: google-cloud-monitoring
Version: 2.2.1
Summary: Stackdriver Monitoring API client library
Home-page: https://github.com/googleapis/python-monitoring
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /opt/conda/lib/python3.7/site-packages
Requires: proto-plus, google-api-core
Required-by: 
```
#### Steps to reproduce

  1. Difference in version cause issues https://stackoverflow.com/questions/64337089/attributeerror-module-google-cloud-monitoring-v3-types-has-no-attribute-metr
  2. Need to get version from library at runtime

#### Code example

```python
>>> from google.cloud import monitoring_v3
>>> monitoring_v3.VERSION
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'google.cloud.monitoring_v3' has no attribute 'VERSION'
>>> monitoring_v3.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'google.cloud.monitoring_v3' has no attribute '__version__'
```

#### Stack trace
N/A

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
Hi @gogasca,

I found a solution to get the version from https://stackoverflow.com/a/32965521 . I'm going to close this off as resolved but please feel free to re-open the issue if you require more information. 

Python >= 3.8
```
from importlib.metadata import version
version('google-cloud-monitoring')
```

Python < 3.8
```
import pkg_resources
pkg_resources.get_distribution('google-cloud-monitoring').version
```
