### ISSUE TITLE
chore: references to "python-docs-samples" master branch

### ISSUE THREAD

**Issue by nicain** [googleapis/python-monitoring#212]
During the master --> main migration, I noticed references inside of AUTHORING_GUIDE.md files that point to the master branch of https://github.com/GoogleCloudPlatform/python-docs-samples

After that repo is migrated, we will need to circle back to this repo (and potentially others) and fix these references

- [x] samples/AUTHORING_GUIDE.md
- [x] samples/CONTRIBUTING.md
- [ ] samples/snippets/v3/alerts-client/noxfile_config.py
- [ ] samples/snippets/v3/cloud-client/noxfile_config.py

xref: https://github.com/googleapis/google-cloud-python/issues/10579

**Comment by meredithslota** [comment]
It looks like some of these updates were made in https://github.com/googleapis/python-monitoring/pull/256 (specifically, the AUTHORING and CONTRIBUTING guide).

**Comment by meredithslota** [comment]
And for the v3 links, those files no longer exist, as the samples have been migrated: https://github.com/googleapis/python-monitoring/tree/main/samples/snippets --> https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/monitoring/snippets/v3
