### ISSUE TITLE
Monitoring: Provide ability to filter by user labels.

### ISSUE THREAD

**Issue by gtseres** [googleapis/python-monitoring#3]
**Is your feature request related to a problem? Please describe.**
It would be very useful to have the ability to filter based on user labels, e.g. a label that we have added to a GKE container that ends up in the user_labels section in Stackdriver. This kind of filtering is possible via the UI/API AFAIK, using the `metadata.user_labels` field.

 **Describe the solution you'd like**
Exposing this field to the Python SDK

 **Describe alternatives you've considered**
Using the API, but it's always better to have this functionality into the SDK

**Comment by parthea** [comment]
I'm going to close this issue as obsolete as the feature request is more than 3 years old. If any functionality is missing from the API, please file a request with the API team in the [public issue tracker](https://cloud.google.com/support/docs/issue-trackers). The client library code is automatically generated using the *.proto files [here](https://github.com/googleapis/googleapis/tree/master/google/monitoring/v3). Please open a new issue if the feature request is still needed.
