### ISSUE TITLE
Accidentally definition of interval in snippets.py in v3/cloud-client

### ISSUE THREAD

**Issue by Lennerados** [googleapis/python-monitoring#472]
Hi,
in [this](https://github.com/googleapis/python-monitoring/blob/HEAD/samples/snippets/v3/cloud-client/snippets.py#L92) file on line 92, `interval` is initialized but never used, since it is properly redefined 5 lines later. I think this is not done on purpose and might exist by accident (also because no other example has this definition).

This code snippet is also on the official [cloud.google.com](https://cloud.google.com/monitoring/custom-metrics/reading-metrics#timeseries-list-data) documentation.

**Comment by meredithslota** [comment]
These samples have been migrated to https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/monitoring/snippets/v3 — I think the issue persists here: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/monitoring/snippets/v3/cloud-client/snippets.py#L92 so I'm going to try to move this issue to the correct repo.

**Comment by meredithslota** [comment]
Closing in favor of the new issue.
