### ISSUE TITLE
UptimeCheckServiceClient.list_uptime_check_ips() returns unrecognized UptimeCheckRegion enum value

### ISSUE THREAD

**Issue by arvid-m** [googleapis/python-monitoring#523]
#### Environment details

  - OS type and version: macOS 12.6
  - Python version: `3.10.8`, also same behaviour in docker image `python:3.9-alpine`.
  - pip version: `22.2.2`
  - `google-cloud-monitoring` version: `2.14.0`

#### Steps to reproduce

  1. `pip install google-cloud-monitoring`
  2. Run code below

#### Code example

```python
from google.cloud import monitoring_v3
gcp_client = monitoring_v3.UptimeCheckServiceClient()
ips = gcp_client.list_uptime_check_ips(request={})
for ip in ips:
    print(ip)
```

#### Stack trace
```
env/lib/python3.10/site-packages/proto/marshal/rules/enums.py:37: UserWarning: Unrecognized UptimeCheckRegion enum value: 6
  warnings.warn(
env/lib/python3.10/site-packages/proto/marshal/rules/enums.py:37: UserWarning: Unrecognized UptimeCheckRegion enum value: 5
  warnings.warn(
env/lib/python3.10/site-packages/proto/marshal/rules/enums.py:37: UserWarning: Unrecognized UptimeCheckRegion enum value: 7
  warnings.warn(
```

Pip freeze:
```
attrs==22.2.0
beautifulsoup4==4.11.1
cachetools==5.2.1
certifi==2022.12.7
charset-normalizer==3.0.1
cloudflare==2.11.1
google-api-core==2.11.0
google-auth==2.16.0
google-cloud-monitoring==2.14.0
googleapis-common-protos==1.58.0
grpcio==1.51.1
grpcio-status==1.51.1
idna==3.4
jsonlines==3.1.0
proto-plus==1.22.2
protobuf==4.21.12
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyYAML==6.0
requests==2.28.2
rsa==4.9
six==1.16.0
soupsieve==2.3.2.post1
urllib3==1.26.14
```

Looking at the `enum` [code](https://github.com/googleapis/googleapis/blob/master/google/monitoring/v3/uptime.proto#L88), numbers above 4 doesn't exists.

**Comment by parthea** [comment]
I filed an issue with the API team via the [public issue tracker](https://cloud.google.com/support/docs/issue-trackers#trackers-list) to request to make the enum definitions public. See https://issuetracker.google.com/issues/278709747 . I'm going to close this issue as a duplicate. Please follow the progress in https://issuetracker.google.com/issues/278709747 .
