### ISSUE TITLE
Failure to import the module (No module named 'google.cloud.monitoring_v3.proto.metric_pb2')

### ISSUE THREAD

**Issue by mezhaka** [googleapis/python-monitoring#58]
**Describe your environment**

```
(opentelemetry-bug) ant@ferrum opentelemetry % python
Python 3.8.3 (default, May 19 2020, 13:54:14)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.architecture()
('64bit', '')
>>> platform.mac_ver()
('10.15.7', ('', '', ''), 'x86_64')
```

**Steps to reproduce**

```
mkdir opentelemetry-bug && cd opentelemetry-bug && python3 -m venv opentelemetry-bug
source opentelemetry-bug/bin/activate
pip install --quiet opentelemetry-exporter-cloud-monitoring
echo "from opentelemetry.exporter.cloud_monitoring import CloudMonitoringMetricsExporter" > bug.py
python bug.py
```

Observe the error:
```
Traceback (most recent call last):
  File "bug.py", line 1, in <module>
    from opentelemetry.exporter.cloud_monitoring import CloudMonitoringMetricsExporter
  File "/Users/ant/t/opentelemetry-bug/opentelemetry-bug/lib/python3.8/site-packages/opentelemetry/exporter/cloud_monitoring/__init__.py", line 9, in <module>
    from google.cloud.monitoring_v3.proto.metric_pb2 import TimeSeries
ModuleNotFoundError: No module named 'google.cloud.monitoring_v3.proto.metric_pb2'
```

**What is the expected behavior?**
Not fail

**What is the actual behavior?**
Exception

**Additional context**
My guess is that the issue is due to the release google-cloud-monitoring 2.0.0 on 2020-10-06 (https://pypi.org/project/google-cloud-monitoring/).  I tried to pin the version to <2 in the virtual environment and it helped:

```
pip install --quiet "google-cloud-monitoring<2"
python bug.py
```
Worked without any error.

**Comment by busunkim96** [comment]
There are breaking changes in `2.0.0`, so any code written for the `1.0.0` surface needs to be updated.

https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/de6b560ca2b48bf28237b92928dd46408980e47d/opentelemetry-exporter-google-cloud/setup.cfg#L29

> @mezhaka the trace and metrics exporters have been combined into a single package [opentelemetry-exporter-google-cloud](https://pypi.org/project/opentelemetry-exporter-google-cloud/) and moved into [this repo](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python). The other one packages need to be deleted, but there is still some traffic to them so they are sitting around 🙁
> 
> > I tried to pin the version to <2 in the virtual environment and it helped
> 
> Yes that's right, the dependency on `google-cloud-monitoring` was not pinned in that release which causes this issue. Switch your package to [opentelemetry-exporter-google-cloud](https://pypi.org/project/opentelemetry-exporter-google-cloud/) and everything should be working with the latest version of OTel Python.
