### ISSUE TITLE
module error for 'TimeSeries'

### ISSUE THREAD

**Issue by immusk** [googleapis/python-monitoring#59]
from google.cloud import monitoring_v3
>>> series = monitoring_v3.TimeSeries()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'TimeSeries'

getting this error while trying to create timeseries data.
please help on this.

**Comment by busunkim96** [comment]
Hi @immusk,

I'm not able to reproduce the error.

Please try installing the library in a new virtualenv. If that does not work for you, let us know which version of the library you are using (`pip show google-cloud-monitoring`).

```
python3 -m venv env
source env/bin/activate
python3 -m pip install google-cloud-monitoring
```

**Comment by immusk** [comment]
Hi @busunkim96 

Thanks for the quick help, I was using python2.7 version, after upgrading to python3, it is working fine now.
