### ISSUE TITLE
MetricServiceClient returns different results for fixed interval

### ISSUE THREAD

**Issue by svenmueller** [googleapis/python-monitoring#64]
#### Environment details

  - OS type and version: macOS 10.15.6
  - Python version: 3.8.5
  - pip version: 20.2.2
  - `google-cloud-monitoring` version: 1.1.0

#### Steps to reproduce

I do see different results for the same query (all parameter values are fixed), which I can't understand currently. Any idea why this can happen? Is this something expected?

  1. Execute the provided example function multiple times
  2. You will see different results even though the query uses interval with fixed start/end time

#### Code example

```python
from google.cloud import monitoring_v3
import time

def list_time_series_aggregate(project_id):
    # [START monitoring_read_timeseries_align]
    client = monitoring_v3.MetricServiceClient()
    project_name = client.project_path(project_id)
    interval = monitoring_v3.types.TimeInterval()
    # fixed point in time, offset 7 days
    interval.end_time.seconds = 1607634588
    interval.end_time.nanos = 836217000
    interval.start_time.seconds = 1607029788
    interval.start_time.nanos = 836217000
    aggregation = monitoring_v3.types.Aggregation()
    aggregation.alignment_period.seconds = 604800 # 7 days

    aggregation.per_series_aligner = (
        monitoring_v3.enums.Aggregation.Aligner.ALIGN_SUM)
    aggregation.cross_series_reducer = (
        monitoring_v3.enums.Aggregation.Reducer.REDUCE_SUM)

    results = client.list_time_series(
        project_name,
        'metric.type="compute.googleapis.com/instance/cpu/utilization"',
        interval,
        monitoring_v3.enums.ListTimeSeriesRequest.TimeSeriesView.FULL,
        aggregation)

    print(list(results)[0].points[0].value.double_value)
```

Thx Sven

**Comment by busunkim96** [comment]
Hi @svenmueller,

It looks like this is a question about API behavior. Please open a bug on the Monitoring API issue tracker: https://issuetracker.google.com/savedsearches/559785 

Thanks!
